"""add workflow step description

Revision ID: 384c14b4849a
Revises: fa3e066bc781
Create Date: 2026-07-25 23:11:59.483059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384c14b4849a'
down_revision: Union[str, Sequence[str], None] = 'fa3e066bc781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_steps', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_steps', 'description')
    # ### end Alembic commands ###
