"""add storage connections and document version storage fields

Revision ID: 8ba92027c057
Revises: 384c14b4849a
Create Date: 2026-07-26 00:18:43.258412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.domain.shared.encrypted_json


# revision identifiers, used by Alembic.
revision: str = '8ba92027c057'
down_revision: Union[str, Sequence[str], None] = '384c14b4849a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('S3', 'GCS', 'MINIO', 'GOOGLE_DRIVE', 'ONEDRIVE', 'LOCAL', name='storageprovider'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONNECTED', 'ERROR', 'DISCONNECTED', name='connectionstatus'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'provider', name='uq_conn_org_provider')
    )
    op.create_index(op.f('ix_storage_connections_organization_id'), 'storage_connections', ['organization_id'], unique=False)
    op.create_table('storage_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_connection_id', sa.Integer(), nullable=False),
    sa.Column('secrets', app.domain.shared.encrypted_json.EncryptedJSON(), nullable=False),
    sa.ForeignKeyConstraint(['storage_connection_id'], ['storage_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_credentials_storage_connection_id'), 'storage_credentials', ['storage_connection_id'], unique=True)
    # SQLite can't ALTER a table to add a foreign key constraint directly --
    # batch mode does the copy-and-move strategy Alembic's SQLite dialect needs.
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_connection_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('storage_key', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('original_filename', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('content_type', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('size_bytes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('source_provider', sa.Enum('S3', 'GCS', 'MINIO', 'GOOGLE_DRIVE', 'ONEDRIVE', 'LOCAL', name='storageprovider'), nullable=True))
        batch_op.add_column(sa.Column('source_external_id', sa.String(length=300), nullable=True))
        batch_op.create_foreign_key('fk_document_versions_storage_connection', 'storage_connections', ['storage_connection_id'], ['id'])
        batch_op.drop_column('content_ref')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_ref', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_constraint('fk_document_versions_storage_connection', type_='foreignkey')
        batch_op.drop_column('source_external_id')
        batch_op.drop_column('source_provider')
        batch_op.drop_column('size_bytes')
        batch_op.drop_column('content_type')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('storage_key')
        batch_op.drop_column('storage_connection_id')
    op.drop_index(op.f('ix_storage_credentials_storage_connection_id'), table_name='storage_credentials')
    op.drop_table('storage_credentials')
    op.drop_index(op.f('ix_storage_connections_organization_id'), table_name='storage_connections')
    op.drop_table('storage_connections')
    # ### end Alembic commands ###
