"""add per-contract ai_config

Revision ID: c2e992f03ef4
Revises: a578bf9308da
Create Date: 2026-07-27 11:58:35.933079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e992f03ef4'
down_revision: Union[str, Sequence[str], None] = 'a578bf9308da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'contracts',
        sa.Column('ai_config', sa.JSON(), nullable=False, server_default='{}'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'ai_config')
    # ### end Alembic commands ###
