from typing import Protocol

from app.domain.users.models import Role, User, UserSession


class RoleRepository(Protocol):
    async def add(self, role: Role) -> None: ...

    async def get(self, role_id: int) -> Role | None: ...

    async def get_by_slug(self, organization_id: int, slug: str) -> Role | None: ...

    async def list_for_organization(self, organization_id: int) -> list[Role]: ...

    async def list_for_agent(self, agent_id: int) -> list[Role]: ...


class UserRepository(Protocol):
    async def add(self, user: User) -> None: ...

    async def get(self, user_id: int) -> User | None: ...

    async def get_by_email(self, email: str) -> User | None: ...

    async def list_for_organization(self, organization_id: int) -> list[User]: ...


class UserSessionRepository(Protocol):
    async def add(self, session: UserSession) -> None: ...

    async def get_by_token(self, token: str) -> UserSession | None: ...

    async def delete(self, token: str) -> None: ...
